/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.saburi.smartcorder.java;

import com.saburi.smartcorder.utils.Enums;
import com.saburi.smartcorder.utils.Utilities;

/**
 *
 * @author CLINICMASTER13
 */

public class JavaClass {

    protected String packageName = "";
    protected String name = "";
    protected String imports = "";
    protected String variables = "";
    protected String contructors = "";
    protected String properties = "";
    protected String methods = "";

    public JavaClass(String name) {
        this.name = name;
    }

//    for interfaces
    public JavaClass(String packageName, String name, String imports, String methods) {
        this.packageName = packageName;
        this.name = name;
        this.imports = imports;
        this.methods = methods;
    }

    public JavaClass(String packageName, String name, String imports, String variables, String contructors, String properties, String methods) {
        this.packageName = packageName;
        this.name = name;
        this.imports = imports;
        this.variables = variables;
        this.contructors = contructors;
        this.properties = properties;
        this.methods = methods;
    }

    public String makeNoArgConstructor() {
        return "public " + this.name + "(){\n}";
    }

    public String makeClass() {
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + "public class " + this.name + "{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }

    public String makeClass(String superClass) {
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + "public class " + this.name + "  extends " + superClass + "{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }

    public String makeClass(String superClass, String annotations) {
        
        String extendRecord = !superClass.equals("")?" extends " + superClass: "";        
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + annotations + "\n"
                + "public class " + this.name  + extendRecord + "{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }

    public String makeClassImp(String _Interface) {
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + "public class " + this.name + "  implements " + _Interface + "{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }

    public String makeClass(Enums.EntityTypes entityTypes, String imp, String annotation) {
        return """
               /*
                Sam Buriima
               generated by Saburi Tools
               */
               package """.concat(" ") + packageName + ";\n\n"
                + this.imports + "\n\n"
                + annotation + "\n"
                + "public class " + this.name + " extends " + Utilities.getFullParentEntity(entityTypes) + " "+imp+"{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }

    public String makeClassImp(String _Interface, String annotation) {
        return """
               /*
                Sam Buriima
               generated by Saburi Tools
               */
               package """ + packageName + ";\n\n"
                + this.imports + "\n\n"
                + annotation + "\n"
                + "public class " + this.name + " implements " + _Interface + "{\n\n"
                + this.variables + "\n"
                + this.contructors + "\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";
    }
    
     public String makeInterface() {
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + "public interface " + this.name + "{\n\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";

    }

    public String makeInterfaceExt(String superInterface) {
        return "/*\n Sam Buriima\n"
                + "generated by Saburi Tools\n"
                + "*/\n"
                + "package " + packageName + ";\n\n"
                + this.imports + "\n\n"
                + "public interface " + this.name + "  extends " + superInterface + "{\n\n"
                + this.properties + "\n"
                + this.methods + "\n\n"
                + "}";

    }
}
